spring:
  application:
    name: kafka-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: 1


server:
  port: ${PORT:0}

eureka:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
