spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8761}

eureka:
  shouldUseDns: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    eureka-server-connect-timeout-seconds: 60
    eureka-server-read-timeout-seconds: 15
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  server:
    expected-client-renewal-interval-seconds: 20

  instance:
    hostname: my-eureka-server.com
    lease-expiration-duration-in-seconds: 70
