spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8761}

eureka:
  shouldUseDns: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    eureka-server-connect-timeout-seconds: 60
    eureka-server-read-timeout-seconds: 15
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
  server:
    expected-client-renewal-interval-seconds: 20
