spring:
  application:
    name: kafka-producer
#  kafka:
#    bootstrap-servers: localhost:9092


server:
  port: ${PORT:0}

eureka:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
